version: "3"
services:
        frontend:
                build: ./server
                restart: always
                ports:
                        - ${SERVICE_PORT}:${SERVICE_PORT}
                container_name: ${NAME}
                image: ${NAME}:${VERSION}
                pull_policy: never
                env_file:
                        - .env
                command: >
                  sh -c  "service apache2 restart && sleep infinity"
                networks:
                        script_network:
                                ipv4_address: 10.0.11.2


networks:
 script_network:
  name: ${NAME}_network
  driver: bridge
  ipam:
   config:
    - subnet: 10.0.11.0/29
      gateway: 10.0.11.1