version: "3"
services:
        teste_gt:
                build: ./server
                restart: always
                environment:
                        - .env
                ports:
                        - 5500:5500
                container_name: "1.0"
                image: teste_gt/teste:${VER}
                pull_policy: never
                command: >
                  sh -c  "service apache2 restart && sleep infinity"
                networks:
                        test_network:
                                ipv4_address: 10.0.11.2


networks:
 test_network:
  driver: bridge
  ipam:
   config:
    - subnet: 10.0.11.0/29
      gateway: 10.0.11.1