name: githubworkflow

on:
  push:
    branches: [ "main" ]
    

jobs:
  build:
    runs-on: self-hosted
    environment: DATABASE
    steps:
    - uses: actions/checkout@v3
    - name: create env variables
      id: env-generator
      run: 
        echo "::echo::off"
        echo DB_HOST=${{ secrets.DB_HOST }} >> GITHUB_OUTPUT
        echo DB_USER=${{ secrets.DB_USER }} >> GITHUB_OUTPUT
        echo DB_PASS=${{ secrets.DB_PASS }} >> GITHUB_OUTPUT
        echo DB_PORT=${{ secrets.DB_PORT }} >> GITHUB_OUTPUT
        echo DB_BASE=${{ secrets.DB_BASE }} >> GITHUB_OUTPUT
        echo VERSION=${{ vars.VERSION }} >> GITHUB_OUTPUT
        echo NAME=${{ vars.NAME }} >> GITHUB_OUTPUT
        echo "::echo::on"

    - name: create env file
      env:
        ENV_FILE: server/app/.env
      run: |
        touch ${ENV_FILE}
        {
          echo '${{ fromJSON(steps.env-generator.outputs.body) }}'
        } >> ${ENV_FILE}

    - name: Build and deploy
      run: docker-compose -f "docker-compose.yml" up -d --build --force-recreate