name: githubworkflow

on:
  push:
    branches: [ "main" ]
    

jobs:

  build:
    runs-on: self-hosted
    environment: DATABASE
    steps:
    - uses: actions/checkout@v3
    - name: build and deploy project
      run: |
        echo DB_HOST=${{ secrets.DB_HOST }} >> server/app/.env
        echo DB_USER=${{ secrets.DB_USER }} >> server/app/.env
        echo DB_PASS=${{ secrets.DB_PORT }} >> server/app/.env
        echo DB_PORT=${{ secrets.DB_PORT }} >> server/app/.env
        echo DB_BASE=${{ secrets.DB_BASE }} >> server/app/.env

        docker-compose -f "docker-compose.yml" up -d --build --force-recreate
      env:
        # DB_HOST: ${{ secrets.DB_HOST }}
        # DB_USER: ${{ secrets.DB_USER }}
        # DB_PASS: ${{ secrets.DB_PASS }}
        # DB_PORT: ${{ secrets.DB_PORT }}
        # DB_BASE: ${{ secrets.DB_BASE }}
        STAGE: ${{ vars.STAGE }}