name: githubworkflow

on:
  push:
    branches: [ "main" ]
    

jobs:
  build:
    runs-on: self-hosted
    environment: DATABASE
    steps:
    - uses: actions/checkout@v3
    - name: create env variables
      env:
        ENV_FILE: server/app/.env
      run: |
        touch ${ENV_FILE}
        echo DB_HOST=${{ secrets.DB_HOST }} >> ${ENV_FILE}
        echo DB_USER=${{ secrets.DB_USER }} >> ${ENV_FILE}
        echo DB_PASS=${{ secrets.DB_PASS }} >> ${ENV_FILE}
        echo DB_PORT=${{ secrets.DB_PORT }} >> ${ENV_FILE}
        echo DB_BASE=${{ secrets.DB_BASE }} >> ${ENV_FILE}

        echo NAME=${{ vars.NAME }} >> ${ENV_FILE}
        echo STAGE=${{ vars.STAGE }} >> ${ENV_FILE}
        echo VERSION=${{ vars.VERSION }} >> ${ENV_FILE}

    - name: Build and deploy
      run: docker-compose -f "docker-compose.yml" up -d --build --force-recreate