name: githubworkflow

on:
  push:
    branches: [ "main" ]
    

jobs:

  build:
    runs-on: ubuntu-latest
    environment: DATABASE
    steps:
    - uses: actions/checkout@v3
    - name: build and deploy project
      run: |
        echo Password is $STAGE
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_BASE: ${{ secrets.DB_BASE }}
        STAGE: ${{ vars.STAGE }}

      run: |
        env
      
      # run: docker-compose -f "docker-compose.yml" up -d --build --force-recreate
