name: githubworkflow

on:
  push:
    branches: [ "main" ]
    

jobs:

  build:
    runs-on: self-hosted
    environment: DATABASE
    steps:
    - uses: actions/checkout@v3
    - name: build and deploy project
      env:
        DB_HOST: '167.250.153.182'
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_BASE: ${{ secrets.DB_BASE }}
        
      run: docker-compose -f "docker-compose.yml" up -d --build --force-recreate
