name: githubworkflow

on:
  push:
    branches: [ "main" ]
    

jobs:

  build:
    runs-on: self-hosted
    environment: DATABASE
    steps:
    - uses: actions/checkout@v3
    - name: build and deploy project
      run: |
        touch .env
        echo DB_HOST=$DB_HOST >> .env
        echo DB_USER=$DB_USER >> .env
        echo DB_PASS=$DB_PASS >> .env

        docker-compose -f "docker-compose.yml" up -d --build --force-recreate
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_BASE: ${{ secrets.DB_BASE }}
        STAGE: ${{ vars.STAGE }}