name: githubworkflow

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: compose project
      run: docker-compose -f "docker-compose.yml" up -d --build --force-recreate
